apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
  namespace: ckad-1312
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: "/"
